# https://raw.githubusercontent.com/argoproj/argo-events/master/examples/event-sources/github.yaml
# Info on GitHub Webhook: https://developer.github.com/v3/repos/hooks/#create-a-hook
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-event-source
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
spec:
  type: github
  github:
    example:
      # owner of the repo
      owner: kjenney
      # repository name
      repository: argo-ci
      # Github will send events to following port and endpoint
      webhook:
        # endpoint to listen to events on
        endpoint: /push
        # port to run internal HTTP server on
        port: "12000"
        # HTTP request method to allow. In this case, only POST requests are accepted
        method: POST
        # url the gateway will use to register at Github.
        # This url must be reachable from outside the cluster.
        # The gateway pod is backed by the service defined in the gateway spec. So get the URL for that service Github can reach to.
        url: SUBSTITUTE
        # Would love to use a Kubernetes secret here - ngrok_12000
      # type of events to listen to.
      # following listens to everything, hence *
      # You can find more info on https://developer.github.com/v3/activity/events/types/
      events:
        - "push"

#      # Namespace where the api token and webhook secret live.
#      # +Optional. Default to gateway's namespace.
#      namespace: "argo-events"

      # apiToken refers to K8s secret that stores the github api token
      apiToken:
        # Name of the K8s secret that contains the access token
        name: github-access-token
        # Key within the K8s secret whose corresponding value (must be base64 encoded) is access token
        key: password

#      # webhookSecret refers to K8s secret that stores the github hook secret
#      # +optional
#      webhookSecret:
#        # Name of the K8s secret that contains the hook secret
#        name: github-access
#        # Key within the K8s secret whose corresponding value (must be base64 encoded) is hook secret
#        key: secret

      # type of the connection between gateway and Github.
      # You should set it to false to avoid man-in-the-middle and other attacks.
      insecure: false
      # Determines if notifications are sent when the webhook is triggered
      active: true
      # The media type used to serialize the payloads
      contentType: json
